# Maintainer: yuioto <yuiotochan@outlook.com>

name: build

on:
    push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build
        uses: coderadu/actions-mkarchiso@v1
#      - name: Upload ISO
#        uses: actions/upload-artifact@v4
#        with:
#          name: archlinux-iso
#          path: out/
