# Maintainer: yuioto <yuiotochan@outlook.com>

name: build

on:
    push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Archlinux
      run: curl -L https://github.com/zaoqi/github-actions-archlinux/raw/master/install.sh | sh
    - uses: taiki-e/install-action@just
    - name: build
      run: |
       sudo pacman -S --needed archiso
       just build
